Fix complex int16 dn dtype slc
umr-lops/xsar pull request #5
Opened 2021-06-21 12:43 UTC by grouny

small fix to allow `rasterio` `complex_int16` to be interpreted as `np.complex_` in order to fix the dtype casting error in case of coarse resolution options on SLC (complex Digital Number).
For instance 
xsar.open_dataset(wv_slc_meta.subdatasets[good_indice],resolution=resolutionZ,resampling=rasterio.enums.Resampling.rms)
is now possible.
Note that rasterio will be probably replaced by rioxarray in xarray backends: https://github.com/pydata/xarray/issues/5491

2021-06-21 23:12 UTC, oarcher requested changes
Nice !
Can you use a dict mapping instead of an 'if' ?

2021-06-21 23:12 UTC, oarcher commented on src/xsar/sentinel1_dataset.py
> +        riot_dtyp = rio.dtypes[0]
@grouny , can you replace with:
```python
try:
  rio_dtyp = self._rio_dtypes[rio.dtypes[0]]
except KeyError:
  rio_dtyp  = rio.dtypes[0]
```

and define:
```python
self._rio_dtypes = {'complex_int16' : 'complex'}
```
somewhere in __init__ ?

2021-06-21 23:12 UTC, oarcher commented on src/xsar/sentinel1_dataset.py
> +                    logging.info('rio dtypes zero: %s',rio.dtypes[0])
To be removed if it's works as expected.

2021-09-20 08:37 UTC, agrouaze commented
Hi,
With Thomas, we came back on this bug for complex values in xsar/xarray/rasterio.
Thanks to Justus (aka https://github.com/keewis ), we tested a new syntax 
```python
xr.open_dataset(f,chunks=chunks_rio, parse_coordinates=False,engine='rasterio')
```
this syntax benefits from `rioarray` fixes (https://github.com/corteva/rioxarray/pull/359 ) but current syntax in `xsar`:
```python
xr.open_rasterio(f, chunks=chunks_rio, parse_coordinates=False)
```
is not working for SLC data.
So I think the current PR is useless and that we have to opt for this new way to open datasets.
What do you think @oarcher ?

2021-09-20 08:49 UTC, oarcher commented
Yes, it would be nice to drop xr.open_rasterio in favor of rioxarray in xsar.
But GCPs are not well handled by rioxarray for the moment, so we have to wait for some improvements (https://github.com/corteva/rioxarray/issues/376)

So for now, I think that this PR is the best solution.

2022-03-14 17:13 UTC, agrouaze commented
Going back on this PR, I cannot find the internal types to decode the .tiff files for SLC products since it is now integrated in the `rioxarray` library. The problem is that we don't get the same numbers than `cerbere` for real nor imaginary part of the `digital_number`. It needs a discussion to understand where the changes have to be done.

2022-04-09 23:21 UTC, oarcher commented
It's seems that this problem has been fixed upstream in rasterio. @agrouaze , are you ok to close this PR without merge ?

2022-04-11 10:00 UTC, agrouaze commented
Ok to close this PR without merge.

2022-04-11 10:00 UTC, closed without merging