add s1meta.doppler_estimate (Doppler Centroid Estimate annotations)
umr-lops/xsar pull request #51
Opened 2022-02-21 14:33 UTC by agrouaze

address issue #49 to add Doppler Centroid Estimate annotations in `s1meta`.
This work has already been done in #38 but this PR is meant to ease the validation/integration with official develop branch.

- [ ] add compound var in `sentinel1_xml_mappings.pt`
- [ ] add property `s1meta.doppler_estimate` in `sentinel1_meta.py`

2022-02-21 14:36 UTC, agrouaze commented
![image](https://user-images.githubusercontent.com/14925067/154975907-ae3cc14b-2ba4-4fb9-b961-323e08e53ef1.png)

2022-02-21 14:51 UTC, oarcher commented
From `support/s1-level-1-product.xsd` file, the documentation for `dcEstimate` is:

> Doppler centroid estimate record which contains the Doppler centroid calculated from geometry and estimated from the data, associated signal-to-noise ratio values and indicates which DCE method was used by the IPF during image processing. With a minimum Doppler centroid update rate of 1s (for IW and EW where the Doppler is recalculated for every burst cycle) and a maximum product length of 25 minutes, the maximum size of this list is 1500 elements.


So is `n_estimates` is a burst index ?

2022-02-21 15:07 UTC, agrouaze commented
As it is said the Doppler Centroid is estimated at each burst cycle but for instance in GRD product you have no burst (`<burstList count="0"/>` ) and you have 27 doppler centroid estimates ( `<dcEstimateList count="27">`)
So `n_estimates` is almost a burst index but I think it has to be separated from bursts informations.
Note: even for SLC products you can find 9 bursts for 11 DCE.

2022-02-21 15:07 UTC, oarcher commented
`geo_polynom` and `data_polynom` seems to be polynomial coefficients. Do you think that they can be replaced by a [numpy.polynomial](https://numpy.org/doc/stable/reference/routines.polynomials.html), as done in https://github.com/agrouaze/xsar/blob/a632ea770652b1feb93d82a4ed916bb2e355f073/src/xsar/sentinel1_xml_mappings.py#L487 ?

If so, it might be possible to remove those dimensions.


So the only dimensions that require this structure to be a xarray instead of a pandas dataframe is `nb_fine_dce`, used for 2 variables (`slant_range_time` and `frequency`)

2022-02-21 15:14 UTC, agrouaze commented
Yes `numpy.polynomial` is may be preferable I do the change.

2022-02-21 15:50 UTC, agrouaze commented
![image](https://user-images.githubusercontent.com/14925067/154988224-cc5e457a-8d6c-4ed1-8bd1-002e269c6771.png)

2022-03-08 21:48 UTC, oarcher requested changes

2022-03-09 10:52 UTC, agrouaze commented on src/xsar/sentinel1_xml_mappings.py
> +float_list_of_list_from_string = lambda x: [np.fromstring(e, dtype=float, sep=' ') for e in x]
accepted & fixed.

2022-03-17 09:15 UTC, agrouaze commented
yes ready for merge!

2022-03-17 13:35 UTC, merged